# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5e21648e853a01c9c1804c5b2af304c7c4e92ff5e632e91b523f87e96de7abdbf3de6cad18f99b6d4bfa743480f918a1ba0c3cea78b9be3d4e7b14fc769d04b

test:
  secret_key_base: 04699f7fd7a99fcc34ac6d5bc5aa04edc3b763089a9ebe8c21bc7242b6cbaf59adac2780cdcfb5eac3a567e1ffd9dc2d28112b8068d2db425595f59dfabc3924

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
